### ISSUE TITLE
Home Assistant

### ISSUE THREAD

**Issue by ilvi80** [maxim-smirnov/homebridge-neptun-smart#1]
Здравствуйте
Скажите, пожалуйста, вашу интеграцию можно как-то использовать в системе Home Assistant?

**Comment by maxim-smirnov** [comment]
Добро дня! Использую только с Homebridge. Как вариант - позволяет испольщовать 3rd party датчики протечки. И настроить автоматизацию на закрытие воды, также можно создать сценарий отпуск и включить в него закрытие кранов.
Насколько я знаю, Home Assist можно интегрировать с Homebridge.

**Comment by bisquit2003** [comment]
> Здравствуйте Скажите, пожалуйста, вашу интеграцию можно как-то использовать в системе Home Assistant?

вы можете поставить в портейнере или докере отдельно хб, и через хк контроллер привязать устройства из хб в ха.
но если вы ищите вариант подключения нептуна в ха - там есть интеграция, как облачная, так и локальная (у меня нормально локальная не заработала, приходится использовать облако)
