### ISSUE TITLE
Neptune ProW+ WiFi

### ISSUE THREAD

**Issue by bisquit2003** [maxim-smirnov/homebridge-neptun-smart#3]
Здравствуйте.
Если есть возможность запилить локальную интеграцию для старенького нептуна, был бы благодарен.

так же не совсем понял какой функционал предоставляет ваш плагин, чем можно управлять, можно ли показания счетчиков снимать...

**Comment by maxim-smirnov** [comment]
Доброго времени суток! На данный момент можно видеть состояние датчиков, как проводных и беспроводных, также вручную перекрыть вентили. 
Я бы с радостью сделал интеграцию с другими устройствами, но просто не имею их на руках. Это делал в первую очередь для себя.
